### PR TITLE
Add rule for assignment alignment

### PR DESCRIPTION
**Pull request by deeky666**
This PR adds a rule for aligning corresponding assignment statements (this does not include arrays).

### CODE REVIEW

**Comment by Michal-sk** [comment]
Out of interest. This is an old threat. But if given the choice to vote for this again, would you guys still be pro?

**Comment by Ocramius** [comment]
@Michal-sk open a new PR with a proposal please

**Comment by deeky666** [comment]
I'm not really a fan of this rule TBH as it creates a lot of noise in diffs, looks akward with long variable names and often requires realignment on adding new entries to a block of assignments. Just my experience though.

**Comment by Ocramius** [comment]
@deeky666 I can live with the diff noise, since it can be easily dealt with (`git blame` even has flags for disabling whitespace changes). Readability is the more important bit here, even if it means more merge conflicts

**Comment by deeky666** [comment]
@Ocramius that's a good point. I can live it as readability is the key here, just a matter of taste ;)

**Comment by Michal-sk** [comment]
I asked because i feel the same way as @deeky666 .For me personally it doesn't add anything to the readability, maybe even worsens it with long and short names and multiple lines (5-6 variables underneath each other). All I would say is "it looks prettier", as in more clean, but when it comes to readying quickly, personally i prefer seeing the value of the variable as soon as possible behind the variable.

**Comment by Michal-sk** [comment]
Regarding the noise. Sure there might be "tricks" to overcome this. But out of the box it will give noise in the diffs as well.

**Comment by greg0ire** [comment]
I feel the same way too, please open a new PR.

**Comment by deeky666** [comment]
Another issue with this rule that is quite annoying: If you have long variable names and other shorter variable names have to be aligned, it is quite likely that you violate the "120 characters per line" rule because there are not many characters available anymore on the right side of the assignment because of the alignment rule. Therefore you will have to split to multiple lines, even though it might fit into one line without alignment. I am not sure if this helps readability either. Of course you might say "then just make the variable names shorter" but this would violate "don't abbreviate" and wouldn't help readability either...

**Comment by Majkl578** [comment]
Surprisingly enough, I am for keeping this rule, increases readability a lot.

**Comment by Michal-sk** [comment]
@Majkl578 why is that "Surprising"? Were you in the past against it?

**Comment by Ocramius** [comment]
Again: not concerned about noise in diffs. It's whitespace and it can be easily dealt with, plus auto-fixers re-align stuff for us anyway.

I'd rather look at a block like this:

```php
$a                        = $b
$wabbadabbababbaglabbaduh = $c;
$d                        = $e;
```

Than a block like:

```php
$a = $b
$wabbadabbababbaglabbaduh = $c;
$d = $e;
```

Being able to *SCAN* code is extremely valuable to identify logical blocks of code. Assigning a bunch of variables is generally something like a "preparation" or "swapping data" step.

**Comment by Majkl578** [comment]
>@Majkl578 why is that "Surprising"? Were you in the past against it?

I had mixed feelings about it in past, I still don't use it in private projects. But for OSS (especially of Doctrine's size), where the code is expected to be read by huge amount of developers, readability prevails.

**Comment by Michal-sk** [comment]
@Majkl578  ok good to know.

@Ocramius funny how people see things different. Personally i prefer block 2. But i do agree that block 1 looks "nicer".

Because i wanted to use this for my personal projects as well, i might just use a fork and change this for my personal projects. I can see how this would help bigger projects like doctrine. Looking nicer / cleaner might also make the code more approachable for others. Tough my personal preference is block 2.

**Comment by Ocramius** [comment]
@Michal-sk I review dozens of thousands lines of code per day: if I'm not able to scan through it I'm much much slower. Remember that we all spend much much much more time reading code than writing it: the writing part is trivial.

**Comment by Michal-sk** [comment]
Thank you for these insights guys. I am not contributing enough to take any stand in this. It was mere for personal preference.

Reading the perspectives of those who have to work with these code bases on a daily base does actually make me believe there are cases where this is beneficial. I will not be opening a PR because I do not believe it will benefit the projects who use this coding standard on a larger scale. Again thank you for the opinions.

**Comment by Majkl578** [comment]
> Because i wanted to use this for my personal projects as well, i might just use a fork and change this for my personal projects.

You can easily exclude the offending rule in your ruleset. I'd suggest to create your own coding standard that imports whole Doctrine CS and then exludes some offending parts:
```xml
<?xml version="1.0"?>
<ruleset name="Some CS">
    <rule ref="Doctrine">
        <exclude name="Generic.Formatting.MultipleStatementAlignment"/>
    </rule>
</ruleset>
```

**Pull request merged**
