### PR TITLE
Removed note about "else if"

### PR DESCRIPTION
**Pull request by phansys**
Removed note about "else if" since it is already part of PSR-2.

### CODE REVIEW

**Comment by Ocramius** [comment]
@phansys no code changes needed?

**Comment by phansys** [comment]
Maybe [this declaration](https://github.com/doctrine/coding-standard/blob/96b3e19c9a151760e0246687a7143f77c0aff3a0/ruleset.xml#L9) should be removed, but I'm not sure why there is a specific declaration since the whole PSR-2 CS is marked before:
```xml
<!-- Import PSR-2 coding standard (base) -->
<rule ref="PSR2"/>

<!-- Disallow else if in favour elseif -->
<rule ref="PSR2.ControlStructures.ElseIfDeclaration.NotAllowed">
    <type>error</type>
</rule>
```

**Comment by Ocramius** [comment]
If PSR2 is imported then we're fine.

**Comment by Ocramius** [comment]
:+1:

**Pull request merged**
