### PR TITLE
Bump patch versions of dependencies

### PR DESCRIPTION
**Pull request by carusogabriel**
Both PHPCS and Slevomat/CS patch updates here are bugfixes related.

### CODE REVIEW

**Comment by Majkl578** [comment]
What do we gain from bumping CodeSniffer and the installer plugin?

**Comment by Ocramius** [comment]
@Majkl578 bumping all deps should be done anyway :+1:

**Comment by Majkl578** [comment]
Yes, but doing it without reason makes it harder for consumers (people building their own CS on top of ours).

**Comment by Ocramius** [comment]
It really doesn't: we don't check those older deps, therefore we don't support them, and therefore we restrict.

Reducing supported ranges actually makes things easier for consumers, as they don't run into weird scenarios caused by dependency permutations that we never saw on our end, and instead makes them just get an installation error instead.

**Comment by Majkl578** [comment]
They do run into scenarios where their CS may work with PHPCS 3.3.0, but not with 3.3.1 due to BC breaks.
Adding one more job with `--prefer-lowest` is probably a good idea anyway.

**Comment by Ocramius** [comment]
@Majkl578 if they don't run with 3.3.1 due to a BC break, they will simply not be able to install this: that's OK.

We're already throwing all the time we can into these projects: let's not add support for larger dependency permutations to the pot.

**Comment by Majkl578** [comment]
Regarding time investment:
_Adding one more CI job (which we need anyway)_ × _Constantly bumping minor versions_

**Comment by Ocramius** [comment]
Add a task that constantly bumps dependencies then 👍

@wyrihaximus you had something for that, no?

**Comment by WyriHaximus** [comment]
@Ocramius meet by buddy @dependabot over at https://dependabot.com/

**Comment by carusogabriel** [comment]
> What do we gain from bumping CodeSniffer

@Majkl578 Some of our issues with array indentation was solved. And, as we are here, let's bump the installer plugin as well.

**Comment by kukulich** [comment]
There may be some more hotfix releases of Slevomat CS in next few days.

**Comment by carusogabriel** [comment]
@kukulich Thanks for that info. Gonna hold this one soo, until our next release.

**Comment by Ocramius** [comment]
Requires another rebase

**Pull request merged**
