### PR TITLE
.gitkeep Sniffs

### PR DESCRIPTION
**Pull request by WyriHaximus**
Created after an idea by @malarzm https://github.com/doctrine/coding-standard/pull/176#issuecomment-616156752
 
Mutually exclusive with: #176

### CODE REVIEW

**Comment by carusogabriel** [comment]
Closing as we're going to move with #176.

Thanks for catching this up, btw!

**Comment by WyriHaximus** [comment]
> Closing as we're going to move with #176.

:+1: 

> Thanks for catching this up, btw!

No problem, better reflection was pretty expressive about not liking this. Had to do some [`unholy`](https://github.com/WyriHaximus/php-broadcast/blob/next-gen/src/Composer/Installer.php#L142-L150) things to temporary work around that.

**Comment by greg0ire** [comment]
For about 10 milliseconds I thought that `retry:` was some python code and then I remembered goto… nice!

**Comment by WyriHaximus** [comment]
To be honest not sure what is worse, the goto, or the exception message "parsing" to get the path and toss it into a `mkdir` 🤐

**Pull request closed without merging**
