### PR TITLE
Sniff to forbid increment and decrement operators

### PR DESCRIPTION
**Pull request by carusogabriel**
As suggested in https://github.com/doctrine/coding-standard/pull/83#pullrequestreview-151625922.

Notice that this isn't an auto-fixable Sniff.

### CODE REVIEW

**Comment by Majkl578** [comment]
>  it can lead to problems, especially when used in expressions.

Right, to clarify my 👎: 
I'd be 👍 if this was only targeting pre/post inc/decrements in expressions.
I see no problem when used standalone, also no problem with pre vs. post increments (irrelevant for standalone statement).

**Comment by Ocramius** [comment]
I use that all the time: from the point of view of newcomers, it is even clearer than the rarely used `++`.

My suggestion still aims at complete eradication of the operator. Remember that this is a stylistic choice, and I personally believe that a simpler instruction set is very often a better one too.

**Comment by kukulich** [comment]
FYI: I plan to release Slevomat CS 4.8 in one week with https://github.com/slevomat/coding-standard/commit/1ae6496b04a5670e4bf7f806df44451bdacd9366 (probably with different name)

**Comment by Ocramius** [comment]
> or part of PSR-12.

Please don't diminish our efforts in designing a coding standard behind someone else's: we are designing a standard that makes things better overall, according to our own view of how to write PHP.
We should not be scared to impose our own view here (nor in any other sniff), as we do indeed use major versions to allow consumers to decide on the rules on their own.

**Comment by greg0ire** [comment]
`for ($i = 0; $i < 10; $i += 1)`

> I use that all the time: from the point of view of newcomers, it is even clearer than the rarely used ++.

Why not use `foreach (range(0, 9) as $i) {` then?

**Comment by greg0ire** [comment]
I thought the point was clarity / avoiding low level constructs / other quirky things like a `for` statement

**Comment by guilhermeblanco** [comment]
:-1: from me

**Comment by ostrolucky** [comment]
> we are designing a standard that makes things better overall, according to our own view of how to write PHP.

That's fine, but I would like to see at least attempt to discuss such controversial rules with PSR-12 group first. Especially if you believe there are strong reasons this is superior. Otherwise we risk introducing rule which will be in direct violation of rules in future state of PSR-12. Also, I disagree with a notion we should go totally separate way in coding style than rest of the world when there is only marginal benefit to do so. In my mind negative of having coding style alien for general PHP community outweighs such marginal pros.

**Comment by carusogabriel** [comment]
Closing as the New Sniff was declined with 5 votes against 2.

**Comment by Ocramius** [comment]
The entire PSR thing is really a separate problem, and should be discussed in a separate issue: we should really just focus on our own preferences, and not on the outside world.

This library is for what we want to do internally first, and for external consumers after that. That's also open for discussion btw, but in a separate thread.

**Comment by malarzm** [comment]
That does sound better

**Pull request closed without merging**
