### PR TITLE
GH Actions: update ubuntu images used

### PR DESCRIPTION
**Pull request by jrfnl**
See: https://github.com/actions/runner-images/issues/6002

### CODE REVIEW

**Comment by jrfnl** [comment]
P.S.: using `ubuntu-latest` would make this more stable, but I presumed it was fixed on a specific ubuntu version for a reason ?

**Comment by kukulich** [comment]
I’m not sure. I think we can change it to “latest”

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
How would it be more stable if it can effectively change from a major version to another? :thinking:

**Comment by jrfnl** [comment]
> How would it be more stable if it can effectively change from a major version to another? 🤔

Well, nothing in this repo actually depends on the Ubuntu version, so the Ubuntu version changing will not have any effect whatsoever. Changing it to `ubuntu-latest` will prevent random failures like the one I encountered today.

**Review by derrabus — APPROVED** [review]

**Comment by greg0ire** [comment]
It might be a decision we've taken for a repo where it mattered, then copy-pasted everywhere without challenging it.

**Comment by ostrolucky** [comment]
I never liked hardcoding ubuntu version in these either. I knew what @greg0ire was going for, but I also knew GH will not want to keep around these old versions forever. Actually I also don't like hardcoding all kinds of other stuff like PHP and Symfony versions, because it has to be maintained and changed all the time. Would be great if there was a way to specify that matrix used is automatically all maintained PHP/Symfony minor versions. But that's off topic, just wanted to rant.

**Review by ostrolucky — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @jrfnl !

**Pull request merged**
