### PR TITLE
ReferenceUsedNamesOnly: Enable searching in annotations

### PR DESCRIPTION
**Pull request by Majkl578**
There is around 300 CS issues in ORM with this enabled.

cc @morozov

### CODE REVIEW

**Comment by morozov** [comment]
I believe this option may have to be disabled for tests. AFAIK, PHPUnit cannot resolve class aliases in `@covers` and `@coversDefaultClass` to their FQNs, so they will contain FQN by design.

**Comment by kukulich** [comment]
It should be ok, the sniff checks only @var, @param, @return and @throws.

**Comment by Majkl578** [comment]
Hah @kukulich was faster. 🐎 
It may be interesting to see it for other annotations (i.e. `@see), but I think it's ok now and covers 99% of use cases.

**Comment by Ocramius** [comment]
:ship:

**Pull request merged**
