### PR TITLE
composer: bump to PHP 5.3, PHPUnit 4.7

### PR DESCRIPTION
**Pull request by TomasVotruba**
Also, I would aim to PHP 5.4, since it's Doctrine\ORM minimal requirement. What do you think?

### CODE REVIEW

**Comment by deeky666** [comment]
@TomasVotruba not sure if that is desired as you could use this coding standard with non Doctrine projects, too. It really is not bound to ORM...

**Comment by TomasVotruba** [comment]
@deeky666 If it's not tested, there no insurance it works. Also, old  Could you link such projects?

Also, it looks like this package [started to be used in April 2015](https://packagist.org/packages/doctrine/coding-standard/stats), so I would not be afraid to drop years old versions.

**Comment by Ocramius** [comment]
@deeky666 5.3 is a decent requirement, same for PHPUnit 4.7 (it's a dev dependency in this PR)

**Comment by TomasVotruba** [comment]
:+1: Thanks

**Pull request merged**
