### PR TITLE
Move to PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by Slamdunk**
- [ ] Map one-to-one `ruleset.xml` to `Config.php` (**I'll do this after the topic discussion**)
- [ ] Update `README.md`

Hi, following https://github.com/doctrine/coding-standard/pull/9#issuecomment-353089579 here I propose to drop [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) in favour of [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) with the following reasons:

1. No XML, just plain PHP
1. Each Fixer class is self-describing, containing:
    1. all documentation
    1. all configurations documentation
    1. code samples for all configurations
1. Tests are plain PHPUnit test cases: implementing new/custom fixers or adding new test cases is straightforward
1. With a simple test like [ConfigTest.php](https://github.com/Slamdunk/doctrine-coding-standard/blob/php_cs_fixer/tests/ConfigTest.php) we can keep up to date with newer fixers and manage deprecations easier
1. Contains precious fixers not present in PHP_CodeSniffer like
    1. `@PHPUnit60Migration:risky`
    1. `@DoctrineAnnotation`
1. It is build upon Symfony components, so has more robust console interactions
1. Strict PHP Version checking and configuration

### CODE REVIEW

**Comment by Slamdunk** [comment]
@Majkl578 I saw your 👎 and I would like to hear your reasoning.

What it really bugs me about PHP_CodeSniffer is how hard it is to understand what a sniffers does.
I want to help FOSS projects, I want to make them better, but if the learning curve of their tools is steep, I give up.

Let's take an example: in the `ruleset.xml` of this project we have this rule:
```xml
<!-- Require EOL at EOF -->
<rule ref="Generic.Files.EndFileNewline"/>
```
As a (wannabe) contributor I want to understand what this sniffer does.

1. Comments are a smell: what needs to be commented, needs to be refactored
1. Google isn't of any help ([link](https://www.google.com/search?gws_rd=cr&hl=en&q=php_codesniffer+Generic.Files.EndFileNewline))
1. Grepping/Finding into the source of PHP_CodeSniffer I find a lot of stuffs with non-trivial code and test cases to understand
1. Until I run it I have no idea if I can automatically fix it or not
1. There is no documentation about what eventual PHP version the fixer is addressed to
1. There is no before-and-after example
1. There is no readable documentation: I am still unable to find where the Wiki or the binary produce what is in the Docs/*xml

And all this for such a simple sniffer.

On the opposite, if you look for what `single_blank_line_at_eof` PHP-CS-Fixer rule does:

1. You can take a look at the global README.md (Google first result is its READE.md [link](https://www.google.com/search?gws_rd=cr&hl=en&q=php-cs-fixer+single_blank_line_at_eof))
1. You can type `php-cs-fixer describe single_blank_line_at_eof` that outputs the documentation and the code samples
1. The tests are raw PhpUnit input->expected (see [SingleBlankLineAtEofFixerTest.php](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/tests/Fixer/Whitespace/SingleBlankLineAtEofFixerTest.php))

**Comment by Ocramius** [comment]
IMO also :-1: on moving to different tooling (and moving back again after a few months, ping-pong style).

The D2 folks are familiar with PHPCS, which is quite OK and well maintained anyway.

Also, the Slevomat coding standard is more than 50% of the reasons to stay with PHPCS.

**Comment by Ocramius** [comment]
PHPCS is a good tool, not a perfect one, but we already did all the work here, so let's settle it this way for now, and we can decide to re-open the topic if it pops up again in a few months.

**Comment by alcaeus** [comment]
Agree with @Ocramius on this. The reasons outlined don't convince me to use php-cs-fixer. As for helping contributors, if a pull request fails with CS errors, we're happy to help them if the error can't be fixed automatically.

**Comment by Slamdunk** [comment]
> IMO also 👎 on moving to different tooling (and moving back again after a few months, ping-pong style).

As mentioned in https://github.com/doctrine/coding-standard/pull/9#issuecomment-353089579 I'm ok with this

> The D2 folks are familiar with PHPCS, which is quite OK and well maintained anyway.

All the Symfony users are familiar to PHP-CS-Fixer, which is a large user base too.

> PHPCS is a good tool, not a perfect one, but we already did all the work here, so let's settle it this way for now, and we can decide to re-open the topic if it pops up again in a few months.

Ok

> The reasons outlined don't convince me to use php-cs-fixer.

I don't get money for PHP-CS-Fixer, and I agree that changing the tools is expensive.
But it will be hard to convince me that, for a new project, PHP_CodeSniffer would be easier/faster to setup and maintain.

> As for helping contributors, if a pull request fails with CS errors, we're happy to help them if the error can't be fixed automatically.

As long as you like that activity, good for you.

**Comment by Majkl578** [comment]
> @Majkl578 I saw your 👎 and I would like to hear your reasoning.

I was on a phone. 😉 

> No XML, just plain PHP

No added value in having it in PHP, you are still using plain strings (unlike i.e. classnames, there it'd be useful).

> Each Fixer class is self-describing

Some of the PHPCS classes as well, some not. But this isn't really issue on our end, documentation should be discussed on PHPCS repo (https://github.com/squizlabs/PHP_CodeSniffer/issues/1752)..

> Tests are plain PHPUnit test cases

So can easily be PHPCS tests, see https://github.com/slevomat/coding-standard/tree/master/tests/Sniffs.

> As a (wannabe) contributor

A _wannabe_ contributor won't read through the ruleset.xml, but read i.e. [CONTRIBUTING.md](https://github.com/doctrine/doctrine2/blob/master/CONTRIBUTING.md), or nothing. Now significant sniffs are also described in README in this repo. Most of the other generic sniffs are simply checks for bad habits / typos etc., like `Generic.PHP.DeprecatedFunction`. Additionally each sniff has pretty verbose error reporting that would be shown during CI inspection for a PR.

> Until I run it I have no idea if I can automatically fix it or not

That's fine, there is no need to know such information before you actually need it. And when you do, you're indicated which error is automatically fixable and which not.

I have no strong opinion about PHP-CS-Fixer, I just have no experience with it. Though I admit, recent PHP-CS-Fixer _spam_/_ad_ in PRs across GH did slightly irritate me (do they giveaway free hats for 5 PR or so?).
The decision in #9/#11 to add new PHPCS sniffs was simply pragmatic: it was already set up, working and used across some repos - no need to switch to different tool unless there is significant gain. Plus there are PHPCS sniffs from Slevomat and I'm not quite there are equvivalents in PHP-CS-Fixed

**Pull request closed without merging**
