### PR TITLE
Ban env functions

### PR DESCRIPTION
**Pull request by gmponos**
Break down #200 and started by the env functions.. also sort the functions to the ones that are alias and the ones that are bad practice to use.

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]

**Comment by simPod** [comment]
Why is it a bad practice?

**Comment by gmponos** [comment]
Inside the xml I have a linked issue.. 

In short words these function are not thread safe and one thread can affect the other

**Review by ostrolucky — CHANGES_REQUESTED** [review]
getenv() is the only way to access parent envs from within children process. It's not always possible to avoid using it.

**Comment by gmponos** [comment]
Hm.. interesting scenario.. 

Shouldn't environmental variables be set on the machine? Once they are set on the machine aren't they set for both processes?

So.. why parent/child processes should use env parameters to communicate with each other?

**Comment by ostrolucky** [comment]
It's not always set "on machine". `FOO=bar php baz.php`

**Comment by gmponos** [comment]
Hi.. I also have a code where I spawn children processes from a parent and I do this too

```
FOO=bar php baz.php
```

But I am passing FOO from the parent to the children during the spawn. The only reason I see that a child will want to read the `FOO` with `getenv` is because `FOO` might have changed.. which for me is a bad practice.

Still I think that this will cover 99% of the case.

Is your concern only for `getenv` and not about `putenv`?  If so I will leave it here for a while.. maybe someone else has more feedback to provide.. and depending will remove it later.

**Comment by simPod** [comment]
Do we have an example where usage of getenv or putenv is actually required then? I'm confused by the discussion a little bit.

**Comment by Ocramius** [comment]
See `doctrine/automatic-releases`: only `putenv()` used there, but I agree that `setenv()` should be banned.

**Comment by gmponos** [comment]
> setenv()

@Ocramius you mean `getenv` ?

**Comment by Ocramius** [comment]
I edited the previous message 😅

**Comment by greg0ire** [comment]
ping @gmponos do you plan on iterating on this? I'm trying to see what could ship in 9.0.0

**Comment by ostrolucky** [comment]
This is unlikely to be merged because of argument I provided. I think we should just close

**Pull request closed without merging**
