### PR TITLE
Move website config to default branch

### PR DESCRIPTION
**Pull request by SenseException**
Adapts the website config to be compatible with the doctrine/doctrine-website#356 changes

Do we need to have 8.0 in the docs?

### CODE REVIEW

**Comment by SenseException** [comment]
This is the last PR that involves moving `.doctrine-project.json` to the default branch. After this I can merge doctrine/doctrine-website#356

**Comment by greg0ire** [comment]
> Do we need to have 8.0 in the docs?

Based on semver I'd say yes, otherwise people might wrongly think some feature that is available exclusively in 8.1 is available in 8.0 too. Also, do we usually skip some minor branches in the docs, in other repositories?

**Comment by SenseException** [comment]
I wasn't sure because there are usually only one entry per major version in the coding-standard. I've added 8.0 now.

**Review by greg0ire — APPROVED** [review]

**Review by ostrolucky — APPROVED** [review]

**Review by carusogabriel — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @SenseException !

**Pull request merged**
