### PR TITLE
Update to PHCS 3.3 and Slevomat/CS 4.6.1

### PR DESCRIPTION
**Pull request by carusogabriel**
Blocked by https://github.com/slevomat/coding-standard/issues/360

### CODE REVIEW

**Comment by lcobucci** [comment]
@carusogabriel could you split this in two PRs? Main thing is that PHPCS 3.3 support can be ported to `v4`

**Comment by carusogabriel** [comment]
@lcobucci Good idea. Gonna update PHPCS and Slevomat/CS here and propose the new sniff in another one :smile:

**Comment by Ocramius** [comment]
Last person approving here: please merge :-P

**Comment by carusogabriel** [comment]
Yeah, we should release a bug fix :(

**Comment by kukulich** [comment]
Is it the bug fix release necessary? What is broken?

**Comment by carusogabriel** [comment]
@kukulich True, we are using PHPCS 3.3 from this PR, not previously.

**Pull request merged**
