### PR TITLE
Require Null Safe Object operator

### PR DESCRIPTION
**Pull request by simPod**
Same as we require Null Coalesce operator, this requires Null Safe operator.

### CODE REVIEW

**Review by ostrolucky — DISMISSED** [review]

**Comment by simPod** [comment]
I wonder if we should create a patch for PHP 8+.

**Review by SenseException — DISMISSED** [review]

**Review by malarzm — DISMISSED** [review]
Patch for PHP 8+ (and generally for versions) sounds like a good idea 👍

**Comment by simPod** [comment]
I've included #257 so we can have CI passing. So from me this is it.

**Review by ostrolucky — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Review by malarzm — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @simPod !

**Comment by greg0ire** [comment]
Hmmmmm… :thinking:  shouldn't this have targeted 10.x ?

**Comment by simPod** [comment]
hmm, maybe 🧐 can we create it?

**Comment by greg0ire** [comment]
Let's revert this, now that the branch exists. Cc @Ocramius

**Pull request merged**
