### PR TITLE
Allow TODO annotation

### PR DESCRIPTION
**Pull request by carusogabriel**
Following https://github.com/doctrine/mongodb-odm/pull/1751#discussion_r173624289.

IMHO makes sense, as it's a good way to track future scopes. Also, if everyone agrees, should we only allow `TODO`, or `todo` is also okay?

### CODE REVIEW

**Comment by Majkl578** [comment]
:-1: TODO should be a comment, not annotation. Also the referenced use case is invalid, `@todo` is only valid on structural elements like class/property/method as per [docs](https://docs.phpdoc.org/references/phpdoc/tags/todo.html).

**Comment by alcaeus** [comment]
For one, I'm not sure if we want to allow this globally: I'm willing to tolerate `@todo` while we work on ODM 2.0, but in general, a PR should not be merged with open todo items.

The only reason why I'm not too happy about overriding this on a per-project level is that we'd have to duplicate the rest of the allowed annotations until the reason to override is gone. Again, if it's for a limited time (e.g. while working on ODM 2.0), I can live with overriding it on a per-project level.

**Comment by Majkl578** [comment]
> The only reason why I'm not too happy about overriding this on a per-project level is that we'd have to duplicate the rest of the allowed annotations

Agreed, duplicating it is sub-optimal. Maybe @kukulich could help here to mitigate the duplication issue, but I'm afraid this will be PHPCS issue and would require support there somehow. :|

**Comment by carusogabriel** [comment]
We are having a lot of false-positives with code like:
```php
// random comment

function foo () {
}
```

The CS starts to warning that this comment should be `/** */` and should have no line between it and the function

**Comment by kukulich** [comment]
@Majkl578 Maybe new option “allAnnotationsAreUseful” (something like this) could be a solution because there is special sniff for forbidden annotions.

**Pull request closed without merging**
