### PR TITLE
Add a test case with switch cases containing return

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by Lctrs** [comment]
Seeing this in one of my project when trying to upgrade to `7.0.0`. `phpcbf` failed to autofix one of my file which contains a `return` inside a switch case.

Maybe 2 sniffers that collide ?

**Comment by lcobucci** [comment]
@Lctrs thanks for you PR!

Would you please move your test to another file? We're trying to isolate things as much as possible and only modifying existing ones when adding a sniff that requires change there.

> Maybe 2 sniffers that collide ?

That does seem to be the case.

**Comment by Lctrs** [comment]
@lcobucci Done.

I tried to add differents testing cases : 
- `break` followed by `case`
- `return` followed by `case`
- `case` with a body and a `return` followed by `case`
- `return` followed by `default`

**Comment by lcobucci** [comment]
@Lctrs that's awesome, thanks for! I'll take a look at it ASAP.

**Comment by Lctrs** [comment]
I just tested locally with #146 and it fixed the problem for me. :tada:

**Comment by Ocramius** [comment]
Hmm, we can't get this through unless green though: is the failure related to this patch?

**Comment by Lctrs** [comment]
@Ocramius I can incorporate this test into #146.

**Comment by Ocramius** [comment]
Moving to `7.0.2` (if still relevant)

**Comment by Lctrs** [comment]
@Ocramius It works now thanks to #146. I updated the PR to add a test case in case you have any interest in it. Otherwise, you can close it :+1:

**Comment by Ocramius** [comment]
Thanks for the ping!

**Pull request closed without merging**
