### PR TITLE
Slevomat CS 7.0.0 and PHPCS 3.6.0

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Review by simPod — APPROVED** [review]

**Review by ostrolucky — APPROVED** [review]

**Review by shadowhand — APPROVED** [review]

**Review by morozov — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @kukulich !

**Comment by shadowhand** [comment]
Can we expect a tagged release today? 🙏

**Comment by ostrolucky** [comment]
You could help convince us to do it if you explain what do you need from 7.0.0 that we are blocking you from

**Comment by morozov** [comment]
There are certain improvements in the Slevomat standard regarding PHP 8.1 support (e.g. https://github.com/slevomat/coding-standard/issues/1171). Current Doctrine standard requires Slevomat `^6`, so it's challenging to use it with PHP 8.1.

**Comment by shadowhand** [comment]
Current version of this package blocks the usage of PHP 8 features such as property promotion, which will result in two different errors errors, depending on number of indented spaces. This means that attempting to use property promotion will *always* result in a phpcs error. There are a variety of other issues related to PHP 8 that are solved in slevomat/coding-standard 7.0 and phpcs 3.6: `match()` (using phpcbf always breaks it), attributes, etc.

Our organization doesn't allow requiring of `-dev` packages, even for developer tooling.

**Comment by greg0ire** [comment]
Done: https://twitter.com/greg0ire/status/1381663675749171210

**Pull request merged**
