### PR TITLE
feat: enable SlevomatCodingStandard.Classes.EnumCaseSpacing sniff

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Review by Ocramius — DISMISSED** [review]

**Comment by Ocramius** [comment]
This should go towards `13.0.x`, which doesn't exist yet

**Review by SenseException — DISMISSED** [review]
> This should go towards 13.0.x, which doesn't exist yet

I guess so. What was the reason for having a minor release like in 11.1?

**Comment by lcobucci** [comment]
I'm unsure regarding expectations, though.

Based on the `fixed` file, is correct to say that we want to force enums to have exactly one, max two line breaks between cases+docblocks (and we're completely fine with a mix between them on the same enum)?

**Comment by simPod** [comment]
@lcobucci it is consistent with defaults in [`AbstractPropertyConstantAndEnumCaseSpacing`](https://github.com/slevomat/coding-standard/blob/34c47b15f852f24008c0f1534b123b2ac124f7e2/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyConstantAndEnumCaseSpacing.php#L33) so the same as we already with ConstantSpacing sniff.

It's defined in these consts:

https://github.com/slevomat/coding-standard/blob/34c47b15f852f24008c0f1534b123b2ac124f7e2/SlevomatCodingStandard/Sniffs/Classes/AbstractPropertyConstantAndEnumCaseSpacing.php#L36-L46

```diff
- max two line breaks between cases+docblocks
+ max one line break between cases+docblocks
```

and it's also ok to have no lines between where there are no docblocks.

**Comment by lcobucci** [comment]
I probably expressed myself too literally... One line break is kind of implicit (otherwise it'd be on the same line) but I understand the meaning 👍

Thanks!

**Review by derrabus — DISMISSED** [review]

**Comment by greg0ire** [comment]
> This should go towards 13.0.x, which doesn't exist yet

Fixed.

**Review by lcobucci — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @simPod !

**Comment by simPod** [comment]
BTW I just went through slevomat's changelog 8.11-8.14 and I know of no more possible additions to Doctrine CS.

**Pull request merged**
