### PR TITLE
Improve documentation about contributing

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
@simPod please review, in case you have better ideas on how to update the patches.

**Review by lcobucci — APPROVED** [review]

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Hmm, did the release automation not create `10.1.x`?

**Comment by greg0ire** [comment]
The state that does that seems to couple the branch creation and the switch to a new minor branch: https://github.com/laminas/automatic-releases/blob/5dbe6fc80071afda56c65e3d77f02575d6bc2300/examples/.github/workflows/release-on-milestone-closed.yml#L39-L47

Since our policy is to switch to the patch branch, it is disabled. So it would depend on the repository: https://github.com/doctrine/.github/blob/eefa7e134fcd134a83c66873796c334fae63d4a9/.github/workflows/release-on-milestone-closed.yml#L53

But I just noticed this one does not use a centralized workflow for some reason.

**Comment by greg0ire** [comment]
I'll create the branches manually. Regarding reusing the workflow, see #286

**Review by ostrolucky — APPROVED** [review]

**Pull request merged**
