### PR TITLE
[WIP] Disallow complex conditional expressions

### PR DESCRIPTION
**Pull request by carusogabriel**
Related to https://github.com/doctrine/dbal/pull/2980#discussion_r161595518

### CODE REVIEW

**Comment by alcaeus** [comment]
@Majkl578 you added this to the 3.0 milestone - is there a sniff we can use or is it just considered a guideline?

**Comment by kukulich** [comment]
I can prepare the sniff. However there are already some new useful sniffs so I do a release of Slevomat CS so everyone can test them and report bugs.

It's also possible to merge some PR here and test them in `dev-master` together.

**Comment by Ocramius** [comment]
Deferred for now

**Comment by carusogabriel** [comment]
@Ocramius Perfect. Should we update across Doctrine's repos as well?

**Comment by kukulich** [comment]
Can someone please make a better explanation what this sniff should do?

Examples would be perfect :)

**Comment by carusogabriel** [comment]
Maybe https://github.com/doctrine/dbal/pull/2980#discussion_r161595518 and https://github.com/doctrine/coding-standard/pull/18#issuecomment-361165900 is something to start but is basically split long conditions (maybe a Sniffers configurable with how many checks are inside it?)

**Comment by lcobucci** [comment]
@carusogabriel @kukulich it might be quite tricky to implement the automatic fix fo this though...

**Comment by Ocramius** [comment]
I'm removing the `4.0.0` milestone here.

I don't think this is worth adding an auto-fixer, btw.

**Comment by carusogabriel** [comment]
Should we gave up on this one?

**Comment by deeky666** [comment]
The question is what does "long" mean here. Does it mean to disallow boolean operators like `&&` and `||`?

**Comment by greg0ire** [comment]
IMO long means longer than 120 chars. I don't understand what's the proposed replacement, a code sample would help, because the related issues shows something quite simple, that doesn't seem applicable to if statements containing big blocks of code.

**Comment by Ocramius** [comment]
> IMO long means longer than 120 chars

`long` as in NPath complexity > 8 or such.

```php
if ($foo === 1 && $bar === 2 && $baz === 3 && $tar === 4) { // too long - 16 paths
```

```php
if ($foo === 1 && $bar === 2 && $baz === 3) { // acceptable - 8 paths
```

**Pull request closed without merging**
