### PR TITLE
Enable UselessConstantTypeHintSniff

### PR DESCRIPTION
**Pull request by Majkl578**

### CODE REVIEW

**Comment by Majkl578** [comment]
@carusogabriel What? There is nothing like _types for constants_. Constants have always static type.

**Comment by Majkl578** [comment]
Also note that `@var` is not allowed for `const`: https://docs.phpdoc.org/references/phpdoc/tags/var.html

**Comment by Ocramius** [comment]
Indeed, constants only have the type of the first assignment, and like anything else in the language, only based on "trust" in the documentation.

**Comment by ostrolucky** [comment]
Not sure about this. You can open constant for inheritance override via late static binding. In such case, consumer needs to know what can they change

**Comment by Ocramius** [comment]
Changing type of a constant via inheritance is also an LSP violation

**Comment by Majkl578** [comment]
@carusogabriel 👍 
I'd like to also propose a rule for PHPStan strict rules to disallow _constant overriding_, I think that makes sense.

**Comment by carusogabriel** [comment]
@Majkl578 Feel free to open an issue there so we can discuss and implement it.

**Pull request merged**
