### PR TITLE
feat: enforce method signature to be on a single line

### PR DESCRIPTION
**Pull request by simPod**
when under 120 symbols

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
I don't agree with this rule: I often declare even simpler methods on multiple lines to ease readability, and ensure that all parameters are immediately visible to the reader.

Enforcing that we compact them to a single row seems unnecessarily forced, to me 🤔

**Comment by simPod** [comment]
I use this sniff for few years now and it helps me autoformat those short methods I leave spread across multiple lines so I find it very helpful.

Though understand your view as well.

**Review by malarzm — CHANGES_REQUESTED** [review]
I'm also kind of 👎 Lately in work we figured that with promoted properties it's better to have arguments on separate lines even if they'd fit in one - it's more readable. Also `#[SensitiveParameter]` is on the horizon which adds yet another "thing" for an argument

**Comment by simPod** [comment]
Ok, this one seems controversial. Thanks for feedback!

**Comment by kukulich** [comment]
Based on the feedback it may be good to enable `RequireMultiLineCall` sniff...

**Comment by malarzm** [comment]
I think this one is best left for common sense :)

**Pull request closed without merging**
